#@ load("@ytt:data", "data")

#@ def gen_image(image, cheese):
#@   return image + ":" + cheese
#@ end

#@ def gen_httproute_path(cheese):
#@   return "/" + cheese 
#@ end

---
kind: Namespace
apiVersion: v1
metadata:
  name: #@ data.values.namespace

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: #@ data.values.gateway.name
  namespace: #@ data.values.namespace
spec:
  gatewayClassName: #@ data.values.gateway.className
  listeners: #@ data.values.gateway.listeners

#@ for/end cheese in data.values.cheeses:
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: #@ cheese.name
  namespace: #@ data.values.namespace
  labels:
    app: cheese
    cheese: #@ cheese.name
spec:
  replicas: #@ data.values.replicas
  selector:
    matchLabels:
      app: cheese
      task: #@ cheese.name
  template:
    metadata:
      labels:
        app: cheese
        task: #@ cheese.name
        version: #@ data.values.version
    spec:
      containers:
      - name: cheese
        image: #@ gen_image(data.values.base_image, cheese.name)
        resources: #@ data.values.resources
        ports:
        - containerPort: #@ data.values.container_port

#@ for/end cheese in data.values.cheeses:
---
apiVersion: v1
kind: Service
metadata:
  name: #@ cheese.name
  namespace: #@ data.values.namespace
spec:
  ports:
  - name: http
    targetPort: #@ data.values.container_port
    port: 80
  selector:
    app: cheese
    task: #@ cheese.name

#@ for/end cheese in data.values.cheeses:
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: #@ cheese.name
  namespace: #@ data.values.namespace
spec:
  parentRefs:
  - kind: Gateway
    name: cheese
    namespace: #@ data.values.namespace
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: #@ gen_httproute_path(cheese.name)
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplaceFullPath
          replaceFullPath: /
  - backendRefs:
    - name: #@ cheese.name
      port: #@ data.values.container_port 
